# Docker Compose file for running the Open-Meteo API on Docker
# Start with: docker compose up
#
# http://0.0.0.0:8080/v1/forecast?latitude=47.1&longitude=8.6&hourly=temperature_2m&models=icon_global
#

volumes:
  open_meteo_database:

x-shared_environment: &shared_environment
  LOG_LEVEL: info

networks:
  open_network_network:

services:

  open-meteo-sync-ecmwf-ifs025:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-sync-wcmf
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync ecmwf_ifs025 temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ ECMWF failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-sync-meteofrance-arpege_world025:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-sync-meteofrance-arpege-world025
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync meteofrance_arpege_world025 temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ MeteoFrance failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-dwd-icon:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-dwd-icon
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync dwd_icon temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ DWD ICON failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-ncepgfs025:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-ncepgfs025
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync ncep_gfs025 temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ NCEP GFS failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-jma-gsm:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-jma-gsm
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync jma_gsm temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ JMA GSM failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-dwd-icon-eu:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-dwd-icon-eu
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync dwd_icon_eu temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ DWD ICON EU failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-dwd-icon-d2:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-dwd-icon-d2
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync dwd_icon_d2 temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ DWD ICON D2 failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-ncep-gfs013:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-ncep-gfs013
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync ncep_gfs013 temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ NCEP GFS013 failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-meteofrance-arpege-europe:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-meteofrance-arpege-europe
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync meteofrance_arpege_europe temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ MeteoFrance Arpege Europe failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-ukmo-global:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-ukmo-global
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync ukmo_global_deterministic_10km temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ UKMO Global failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-cmc-gem-gdps:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-cmc-gem-gdps
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync cmc_gem_gdps temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ CMC GEM GDPS failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-jma-msm:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-jma-msm
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync jma_msm temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ JMA MSM failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-cma-grapes-global:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-cma-grapes-global
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync cma_grapes_global temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ CMA GRAPES Global failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-bom-access-global:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-bom-access-global
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync bom_access_global temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ BOM Access Global failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-knmi-harmonie-arome-europe:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-knmi-harmonie-arome-europe
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync knmi_harmonie_arome_europe temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ KNMI Harmonie Arome Europe failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo-kma-gdps:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-kma-gdps
    networks:
      - open_network_network
    environment:
      <<: *shared_environment
    command: >
      sync kma_gdps temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,wind_direction_10m,precipitation --past-days 3 --repeat-interval 4320 --concurrent 1 || echo '⚠️ KMA GDPS failed'
    volumes:
      - open_meteo_database:/app/data
    restart: always

  open-meteo:
    image: ghcr.io/open-meteo/open-meteo
    container_name: open-meteo-api
    networks:
      - open_network_network
    volumes:
      - open_meteo_database:/app/data
    environment:
      <<: *shared_environment
    ports:
      - "8080:8080"
    user: '0'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]

  weather_station:
    image: weatherstation:latest
    container_name: weatherstation
    depends_on:
      - open-meteo
    networks:
      - open_network_network
    ports:
      - "8110:8110"
    environment:
      - OPEN_METEO_API_URL=http://open-meteo-api:8080
